### ISSUE TITLE
Import metahuman's face crashed in UE5.2

### ISSUE THREAD

**Issue by oncemorego** [rdeioris/glTFRuntime#74] opened 2023-08-22 10:10 UTC
Unreal Editor crashed When imported a metahuman face glb file. 
Blueprints and bone info are in the attached : 

![blender_info](https://github.com/rdeioris/glTFRuntime/assets/1442343/898fa809-fc64-4f18-9c0c-fd7ee6d643a6)
![loading_glb_1](https://github.com/rdeioris/glTFRuntime/assets/1442343/cd453f85-06e1-472e-9892-f34414520640)
![loading_glb_2](https://github.com/rdeioris/glTFRuntime/assets/1442343/cc0fa56f-6010-479b-8390-77dfde7b6b61)

Mesh:
[SK_R.zip](https://github.com/rdeioris/glTFRuntime/files/12407496/SK_R.zip)

**Comment by rdeioris** [comment] 2023-08-22 10:38
@oncemorego thanks for reporting. It is fixed in master. The issue was caused by the file having meshes with empty primitives (that is not valid in gltf specs, but it is not a good reason for crashing ;)

**Closed by rdeioris** 2023-08-22 10:38 UTC
